-- MySQL Script generated by MySQL Workbench
-- Thu Sep 27 15:18:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema absen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ci_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ci_sessions` (
  `id` VARCHAR(40) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ci_sessions_timestamp` (`timestamp` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(100) NULL,
  `user_password` VARCHAR(100) NULL,
  `user_full_name` VARCHAR(255) NULL,
  `user_status` TINYINT(1) NULL DEFAULT 1,
  `user_token` VARCHAR(255) NULL,
  `role_role_id` INT NULL,
  `user_input_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_last_login` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_roles_idx` (`role_role_id` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`role_role_id`)
    REFERENCES `roles` (`role_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `merchants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merchants` (
  `merchant_id` INT NOT NULL AUTO_INCREMENT,
  `merchant_code` VARCHAR(45) NOT NULL,
  `merchant_name` VARCHAR(255) NULL,
  `merchant_tlp` VARCHAR(15) NULL,
  `merchant_address` TEXT NULL,
  `merchant_input_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `merchant_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`merchant_id`, `merchant_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_merchants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_merchants` (
  `user_merchant_id` INT NOT NULL AUTO_INCREMENT,
  `user_merchant_email` VARCHAR(100) NULL,
  `user_merchant_password` VARCHAR(100) NULL,
  `user_merchant_full_name` VARCHAR(255) NULL,
  `user_merchant_status` TINYINT(1) NULL DEFAULT 1,
  `user_merchant_token` VARCHAR(255) NULL,
  `merchant_merchant_id` INT NULL,
  `merchant_merchant_code` VARCHAR(45) NULL,
  `user_merchant_input_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_merchant_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_merchant_last_login` TIMESTAMP NULL,
  PRIMARY KEY (`user_merchant_id`),
  INDEX `fk_user_merchants_merchants1_idx` (`merchant_merchant_id` ASC, `merchant_merchant_code` ASC),
  CONSTRAINT `fk_user_merchants_merchants1`
    FOREIGN KEY (`merchant_merchant_id` , `merchant_merchant_code`)
    REFERENCES `merchants` (`merchant_id` , `merchant_code`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_nip` VARCHAR(45) NOT NULL,
  `employee_full_name` VARCHAR(255) NULL,
  `employee_pob` VARCHAR(45) NULL,
  `employee_dob` DATE NULL,
  `employee_email` VARCHAR(100) NULL,
  `employee_password` VARCHAR(100) NULL,
  `employee_tlp` VARCHAR(15) NULL,
  `employee_address` TEXT NULL,
  `employee_country` VARCHAR(45) NULL,
  `employee_ktp` VARCHAR(16) NULL,
  `employee_npwp` VARCHAR(45) NULL,
  `employee_token` VARCHAR(255) NULL,
  `merchant_merchant_code` VARCHAR(45) NULL,
  `merchant_merchant_id` INT NULL,
  `employee_input_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `employee_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `employee_last_login` TIMESTAMP NULL,
  PRIMARY KEY (`employee_id`, `employee_nip`),
  INDEX `fk_employees_merchants1_idx` (`merchant_merchant_id` ASC, `merchant_merchant_code` ASC),
  CONSTRAINT `fk_employees_merchants1`
    FOREIGN KEY (`merchant_merchant_id` , `merchant_merchant_code`)
    REFERENCES `merchants` (`merchant_id` , `merchant_code`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `presents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `presents` (
  `present_id` INT NOT NULL AUTO_INCREMENT,
  `present_year` YEAR NULL,
  `present_month` INT NULL,
  `present_date` DATE NULL,
  `present_entry_time_1` TIME NULL,
  `present_out_time_1` TIME NULL,
  `present_entry_time_2` TIME NULL,
  `present_out_time_2` TIME NULL,
  `present_out_desc_1` VARCHAR(100) NULL,
  `present_out_desc_2` VARCHAR(100) NULL,
  `present_is_late` TINYINT NULL DEFAULT 0,
  `present_is_before` TINYINT NULL DEFAULT 0,
  `employee_employee_id` INT NULL,
  `employee_employee_nip` VARCHAR(45) NULL,
  PRIMARY KEY (`present_id`),
  INDEX `fk_presents_employees1_idx` (`employee_employee_id` ASC, `employee_employee_nip` ASC),
  CONSTRAINT `fk_presents_employees1`
    FOREIGN KEY (`employee_employee_id` , `employee_employee_nip`)
    REFERENCES `employees` (`employee_id` , `employee_nip`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registers` (
  `register_id` INT NOT NULL AUTO_INCREMENT,
  `register_code` VARCHAR(16) NULL,
  `register_pin` VARCHAR(45) NULL,
  `register_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `register_input_date` DATE NULL,
  `register_due_date` DATE NULL,
  `register_product_name` VARCHAR(255) NULL,
  `register_imei` VARCHAR(255) NULL,
  `register_serial` VARCHAR(255) NULL,
  `register_status` INT(1) NULL,
  `merchant_merchant_id` INT NULL,
  `merchant_merchant_code` VARCHAR(45) NULL,
  PRIMARY KEY (`register_id`),
  INDEX `fk_registers_merchants1_idx` (`merchant_merchant_id` ASC, `merchant_merchant_code` ASC),
  CONSTRAINT `fk_registers_merchants1`
    FOREIGN KEY (`merchant_merchant_id` , `merchant_merchant_code`)
    REFERENCES `merchants` (`merchant_id` , `merchant_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks` (
  `bank_id` INT NOT NULL,
  `bank_vendor` VARCHAR(100) NULL,
  `bank_account` VARCHAR(100) NULL,
  `bank_name` VARCHAR(255) NULL,
  `bank_input_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `bank_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`bank_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rents` (
  `rent_id` INT NOT NULL AUTO_INCREMENT,
  `rent_type` VARCHAR(100) NULL,
  `rent_price` DECIMAL NULL,
  `rent_input_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `rent_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`rent_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `payment_month` INT NULL,
  `payment_total` INT NULL,
  `payment_proof` VARCHAR(255) NULL,
  `payment_name` VARCHAR(255) NULL,
  `payment_account` VARCHAR(100) NULL,
  `payment_status` TINYINT NULL DEFAULT 0,
  `payment_input_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `merchant_merchant_id` INT NULL,
  `merchant_merchant_code` VARCHAR(45) NULL,
  `bank_bank_id` INT NULL,
  `rent_rent_id` INT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_payments_merchants1_idx` (`merchant_merchant_id` ASC, `merchant_merchant_code` ASC),
  INDEX `fk_payments_banks1_idx` (`bank_bank_id` ASC),
  INDEX `fk_payments_rents1_idx` (`rent_rent_id` ASC),
  CONSTRAINT `fk_payments_merchants1`
    FOREIGN KEY (`merchant_merchant_id` , `merchant_merchant_code`)
    REFERENCES `merchants` (`merchant_id` , `merchant_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_banks1`
    FOREIGN KEY (`bank_bank_id`)
    REFERENCES `banks` (`bank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_rents1`
    FOREIGN KEY (`rent_rent_id`)
    REFERENCES `rents` (`rent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
